apiVersion: fraima.io/v1beta1
kind: staticpod
metadata:
    annotations: {}
    labels: {}
    name: ""
spec:
  template:
    metadata:
      labels: {}
      annotations: {}
    spec:
      nodeSelector: {}
      containers:
        - name: ""
          image: ""
          imagePullPolicy: ""
          args: []
          livenessProbe: {}
          readinessProbe: {}
          resources: {}
          env: []
