---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    command:
      - etcd
    args:
    {{- with .Values.pod.etcd }}
      {{- with .containers.etcd }}
    {{- range $key, $val := .noOverrideArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .staticArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .extraArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    image: {{ .image }}
    imagePullPolicy: {{ .imagePullPolicy }}
    livenessProbe: 
      {{- toYaml .livenessProbe | nindent 6 }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    startupProbe:
      {{- toYaml .startupProbe | nindent 6 }}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/certs/etcd
      name: etcd-certs
    - mountPath: /etc/kubernetes/pki/ca
      name: ca
    {{- end }}
  hostNetwork: {{ .hostNetwork }}
  priorityClassName: {{ .priorityClassName }}
  securityContext:
    {{- toYaml .resources | nindent 6 }}
  {{- end }}
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/certs/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /etc/kubernetes/pki/ca
      type: DirectoryOrCreate
    name: ca
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
