---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    command:
      - etcd
    args:
      - --initial-cluster=master-0.cluster-2.dobry-kot.ru=https://master-0.cluster-2.dobry-kot.ru:2380,master-1.cluster-2.dobry-kot.ru=https://master-1.cluster-2.dobry-kot.ru:2380,master-2.cluster-2.dobry-kot.ru=https://master-2.cluster-2.dobry-kot.ru:2380
      - --name={{ .Values.global.hostname }}.{{ .Values.global.clusterName }}.{{ .Values.global.baseDomain }}
      - --initial-advertise-peer-urls=https://{{ .Values.global.hostname }}.{{ .Values.global.clusterName }}.{{ .Values.global.baseDomain }}:2380
      - --advertise-client-urls=https://{{ .Values.global.hostname }}.{{ .Values.global.clusterName }}.{{ .Values.global.baseDomain }}:2379
  {{- with .Values.container.etcd }}
    {{- toYaml .args | nindent 6 }}
    image: {{ .image }}
    imagePullPolicy: {{ .imagePullPolicy }}
    livenessProbe: 
      {{- toYaml .livenessProbe | nindent 6 }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    startupProbe:
      {{- toYaml .startupProbe | nindent 6 }}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/certs/etcd
      name: etcd-certs
    - mountPath: /etc/kubernetes/pki/ca
      name: ca
  {{- end }} 
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/certs/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /etc/kubernetes/pki/ca
      type: DirectoryOrCreate
    name: ca
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}