---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
      - kube-controller-manager
    args:
    {{- with .Values.pod.kubeControllerManager }}
      {{- with .containers.kubeControllerManager }}
    {{- range $key, $val := .noOverrideArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .staticArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .extraArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    image: {{ .image }}
    imagePullPolicy: {{ .imagePullPolicy }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    livenessProbe: 
      {{- toYaml .livenessProbe | nindent 6 }}
    startupProbe:
      {{- toYaml .startupProbe | nindent 6 }}
    {{- end }}
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki/certs
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/pki/ca
      name: k8s-ca
      readOnly: true
    - mountPath: /etc/kubernetes/kube-controller-manager
      name: k8s-kube-controller-manager-configs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: {{ .hostNetwork }}
  priorityClassName: {{ .priorityClassName }}
  securityContext: 
    {{- toYaml .securityContext | nindent 6 }}
  {{- end }} 
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki/certs
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/pki/ca
      type: DirectoryOrCreate
    name: k8s-ca
  - hostPath:
      path: /etc/kubernetes/kube-controller-manager
      type: DirectoryOrCreate
    name: k8s-kube-controller-manager-configs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}