---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver
    command:
    - kube-apiserver
    args:
    {{- with .Values.pod.kubeApiserver }}
      {{- with .containers.kubeApiserver }}
    {{- range $key, $val := .noOverrideArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .staticArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    {{- range $key, $val := .extraArgs }}
      - --{{ $key }}={{ $val }}
    {{- end }}
    image: {{ .image }}
    imagePullPolicy: {{ .imagePullPolicy }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    livenessProbe: 
      {{- toYaml .livenessProbe | nindent 6 }}
    readinessProbe:
      {{- toYaml .readinessProbe | nindent 6 }}
    startupProbe:
      {{- toYaml .startupProbe | nindent 6 }}
    {{- end }}
  ##### Пока не начали тянуть переменные путей сертификатов блоки волюмов не трогаем
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/kubernetes/pki/certs
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/pki/ca
      name: k8s-ca
      readOnly: true
    - mountPath: /etc/kubernetes/kube-apiserver
      name: k8s-kube-apiserver-configs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: {{ .hostNetwork }}
  priorityClassName: {{ .priorityClassName }}
  securityContext: 
    {{- toYaml .securityContext | nindent 6 }}
  {{- end }} 
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /etc/kubernetes/pki/certs
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/pki/ca
      type: DirectoryOrCreate
    name: k8s-ca
  - hostPath:
      path: /etc/kubernetes/kube-apiserver
      type: DirectoryOrCreate
    name: k8s-kube-apiserver-configs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
