---
manifestsDir: /home/geo/projects/fraima/cluster-controller/
manifests:
  - name: etcd
    templatePath: /home/geo/projects/fraima/cluster-controller/template/pod/etcd-template.yaml
  - name: kube-apiserver
    templatePath: /home/geo/projects/fraima/cluster-controller/template/pod/kube-apiserver-template.yaml
  - name: kube-controller-manager
    templatePath: /home/geo/projects/fraima/cluster-controller/template/pod/kube-controller-manager-template.yaml
  - name: kube-scheduler
    templatePath: /home/geo/projects/fraima/cluster-controller/template/pod/kube-scheduler-template.yaml

baseValuesFile: /home/geo/projects/fraima/cluster-controller/base-values.yaml

extraValues:
  global:
    hostname: master-extra
    clusterName: cluster-extra
