---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    command:
      - etcd
    args:
      - --advertise-client-urls=https://master-0.cluster-2.dobry-kot.ru:2379
      - --initial-advertise-peer-urls=https://master-0.cluster-2.dobry-kot.ru:2380
      - --initial-cluster=master-0.cluster-2.dobry-kot.ru=https://master-0.cluster-2.dobry-kot.ru:2380,master-1.cluster-2.dobry-kot.ru=https://master-1.cluster-2.dobry-kot.ru:2380,master-2.cluster-2.dobry-kot.ru=https://master-2.cluster-2.dobry-kot.ru:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd
      - --name=master-0.cluster-2.dobry-kot.ru
      - --cert-file=/etc/kubernetes/pki/certs/etcd/system:etcd-server.pem
      - --key-file=/etc/kubernetes/pki/certs/etcd/system:etcd-server-key.pem
      - --listen-client-urls=https://0.0.0.0:2379
      - --listen-metrics-urls=http://0.0.0.0:2381
      - --listen-peer-urls=https://0.0.0.0:2380
      - --peer-cert-file=/etc/kubernetes/pki/certs/etcd/system:etcd-peer.pem
      - --peer-key-file=/etc/kubernetes/pki/certs/etcd/system:etcd-peer-key.pem
      - --peer-trusted-ca-file=/etc/kubernetes/pki/ca/etcd-ca.pem
      - --trusted-ca-file=/etc/kubernetes/pki/ca/etcd-ca.pem
      - --client-cert-auth=true
      - --data-dir=/var/lib/etcd
      - --peer-auto-tls=true
      - --peer-client-cert-auth=true
      - --strict-reconfig-check=<no value>
    image: k8s.gcr.io/etcd:3.5.3-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/certs/etcd
      name: etcd-certs
    - mountPath: /etc/kubernetes/pki/ca
      name: ca
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
      null
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/certs/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /etc/kubernetes/pki/ca
      type: DirectoryOrCreate
    name: ca
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
